org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17.21

# Mod Properties
mod_version=1.0.0
maven_group=dev.combataudio
archives_base_name=combat-audio-mixer

# Dependencies
fabric_api_version=0.161.0+26.3
